pub trait Input {
    fn new() -> Self;

    fn key_down(&mut self, key: Key);
    fn key_up(&mut self, key: Key);
    fn mouse_down(&mut self, key: MouseButton);
    fn mouse_up(&mut self, key: MouseButton);
    fn update_mouse_position(&mut self, position: (isize, isize));
    fn set_mouse_lock(&mut self, state: bool);
    fn frame_reset(&mut self);

    fn is_mouse_locked(&self) -> bool;
}

#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum MouseButton {
    Primary,
    Secondary,
    Middle,
}

#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Key {
    Backspace = 0x08,
    Tab,
    Enter = 0x0D,
    LeftShift,
    RightShift,
    LeftControl,
    RightControl,
    LeftAlt,
    RightAlt,
    Pause,
    CapsLock,
    Escape = 0x1B,
    Space = b' ',
    PageUp,
    PageDown,
    End,
    Home,
    LeftArrow,
    UpArrow,
    RightArrow,
    DownArrow,
    PrintScreen = 0x2C,
    Insert,
    Delete,
    _0 = b'0',
    _1,
    _2,
    _3,
    _4,
    _5,
    _6,
    _7,
    _8,
    _9,
    A = b'A',
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Windows,
    Menu,
    Numpad0 = 0x60,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadMultiply,
    NumpadAdd,
    NumpadSubtract,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Tilde,
    Dash,
    Equal,
    NumLock = 0x90,
    ScrollLock,
    Comma,
    Period,
    ForwardSlash,
    BackSlash,
    LeftSquareBracket,
    RightSquareBracket,
    SemiColon,
    Quote,
}

impl std::fmt::Display for Key {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Key::Backspace => "Backspace",
                Key::Tab => "Tab",
                Key::Enter => "Enter",
                Key::LeftShift => "Left Shift",
                Key::RightShift => "Right Shift",
                Key::LeftControl => "Left Control",
                Key::RightControl => "Right Control",
                Key::LeftAlt => "Left Alt",
                Key::RightAlt => "Right Alt",
                Key::Pause => "Pause",
                Key::CapsLock => "Caps Lock",
                Key::Escape => "Escape",
                Key::Space => "Space",
                Key::PageUp => "Page Up",
                Key::PageDown => "Page Down",
                Key::End => "End",
                Key::Home => "Home",
                Key::LeftArrow => "Left",
                Key::UpArrow => "Up",
                Key::RightArrow => "Right",
                Key::DownArrow => "Down",
                Key::PrintScreen => "Print Screen",
                Key::Insert => "Insert",
                Key::Delete => "Delete",
                Key::_0 => "0",
                Key::_1 => "1",
                Key::_2 => "2",
                Key::_3 => "3",
                Key::_4 => "4",
                Key::_5 => "5",
                Key::_6 => "6",
                Key::_7 => "7",
                Key::_8 => "8",
                Key::_9 => "9",
                Key::A => "A",
                Key::B => "B",
                Key::C => "C",
                Key::D => "D",
                Key::E => "E",
                Key::F => "F",
                Key::G => "G",
                Key::H => "H",
                Key::I => "I",
                Key::J => "J",
                Key::K => "K",
                Key::L => "L",
                Key::M => "M",
                Key::N => "N",
                Key::O => "O",
                Key::P => "P",
                Key::Q => "Q",
                Key::R => "R",
                Key::S => "S",
                Key::T => "T",
                Key::U => "U",
                Key::V => "V",
                Key::W => "W",
                Key::X => "X",
                Key::Y => "Y",
                Key::Z => "Z",
                Key::Windows => "Windows",
                Key::Menu => "Menu",
                Key::Numpad0 => "Numpad 0",
                Key::Numpad1 => "Numpad 1",
                Key::Numpad2 => "Numpad 2",
                Key::Numpad3 => "Numpad 3",
                Key::Numpad4 => "Numpad 4",
                Key::Numpad5 => "Numpad 5",
                Key::Numpad6 => "Numpad 6",
                Key::Numpad7 => "Numpad 7",
                Key::Numpad8 => "Numpad 8",
                Key::Numpad9 => "Numpad 9",
                Key::NumpadMultiply => "Numpad *",
                Key::NumpadAdd => "Numpad +",
                Key::NumpadSubtract => "Numpad -",
                Key::NumpadDecimal => "Numpad .",
                Key::NumpadDivide => "Numpad /",
                Key::NumpadEnter => "Numpad Enter",
                Key::F1 => "F1",
                Key::F2 => "F2",
                Key::F3 => "F3",
                Key::F4 => "F4",
                Key::F5 => "F5",
                Key::F6 => "F6",
                Key::F7 => "F7",
                Key::F8 => "F8",
                Key::F9 => "F9",
                Key::F10 => "F10",
                Key::F11 => "F11",
                Key::F12 => "F12",
                Key::Tilde => "`",
                Key::Dash => "-",
                Key::Equal => "=",
                Key::NumLock => "Num Lock",
                Key::ScrollLock => "Scroll Lock",
                Key::Comma => ",",
                Key::Period => ".",
                Key::ForwardSlash => "/",
                Key::BackSlash => "\\",
                Key::LeftSquareBracket => "[",
                Key::RightSquareBracket => "]",
                Key::SemiColon => ";",
                Key::Quote => "'",
            }
        )
    }
}
